title: thisispalash.com
author: Palash A.
url: https://thisispalash.com
description: >
  Personal Website/Portfolio of Palash A.

remote_theme: riggraz/no-style-please
theme_config:
  appearance: "dark"
  back_home_text: "home"
  date_format: "%y-%m-%d [%H:%M] | %F" # 21-03-05 [20:33] | EST
  show_description: true
