title: thisispalash[.com]
author: Palash A.
url: https://thisispalash.com
description: >
  dreaming of the big things, failing at the little things.
permalink: /:slug.eth

favicon: "memoji.png"
remote_theme: riggraz/no-style-please
theme_config:
  appearance: "dark"
  back_home_text: "home"
  date_format: "%y-%m-%d" # 21-03-05 [20:33] | EST
  show_description: true

plugins:
  - jekyll-seo-tag
  # - jekyll-feed